### ISSUE TITLE
Deprecate old WSC websites; consolidate resources under org ownership

### ISSUE THREAD

**Issue by deweydell** [WriteSpeakCode/writespeakcode.com#143]
## Summary
Audit and teardown of old WSC sites/digital information so we can have a clean online presence (for ex. things like http://blog.writespeakcode.com/)

## Motivation
This will solve the fact there are a lot of disparate technology settings and no source of truth on who owns what and what's currently live or not.

## Open Questions
- [ ] Access to heroku account

## Acceptance Criteria
- [x] Create list of resources to deprecate
- [ ] Create list of resources to transfer to WSC ownership
- [ ] Document any resources that don't live in this repo with description, location, and how to update
- [ ] Archive any old/irrelevant repos in our org to avoid confusion
- [ ] complete Todos in lists below

### Repos to Archive
- [X] https://github.com/WriteSpeakCode/deprecated_2017
- [X] https://github.com/WriteSpeakCode/assets
- [ ] https://github.com/WriteSpeakCode/raffle
- [ ] https://github.com/WriteSpeakCode/virtuoso
- [ ] https://github.com/WriteSpeakCode/wsc2016
- [x] https://github.com/WriteSpeakCode/raw-template-17

# Old blog
What: http://blog.writespeakcode.com/
Where:  ??

# DNS
What: DNS is where we register records for our domain writespeakcode.com
Where: DNS is under rebecca's account in Dreamhost

Todo:
- [X] reach out to Rebecca
- [ ] transfer to WSC owned account

# 2018 website
What: jekyll site
Where: https://github.com/WriteSpeakCode/writespeakcode.github.io

Todo:
- [ ] take down homepage content
- [ ] transfer to this repo if possible
- [ ] what is this and is it live? https://github.com/WriteSpeakCode/2018.writespeakcode.com

# 2017 website
What: html/css website, hosted via heroku?
Where: https://github.com/WriteSpeakCode/2017.writespeakcode.com

Todo:
- [ ] Remove dependency on heroku
- [ ] transfer to this repo if possible

# 2016 website
What: ruby site on heroku
Where: https://github.com/WriteSpeakCode/2016.writespeakcode.com

Todo:
- how is https://github.com/WriteSpeakCode/wsc2016 related? archive?
- [ ] currently 2016.writespeakcode.com has a SSL cert that expired in June 2019

# 2015/2013 website
What: ??
Where: 
- https://github.com/WriteSpeakCode/website
- https://github.com/WriteSpeakCode/2015.writespeakcode.com

Todo:
2015.writespeakcode.com currently shows the following error:
![Screen Shot 2019-09-28 at 10 30 31 AM](https://user-images.githubusercontent.com/11186572/65818519-1bfcff80-e1e0-11e9-8ef8-d494f77f7f30.png)
