### ISSUE TITLE
Create pages for each chapter

### ISSUE THREAD

**Issue by deweydell** [WriteSpeakCode/writespeakcode.com#22]
# Create a page for each chapter

## Summary

Each chapter will have a page at writespeakcode.com/city. 
The page will contain information like who are the chapter organizers and what are the upcoming events (pulled from meetup API).

### Acceptance Criteria

- [ ] Main page/footer links out chapter pages instead of directly to meetup pages

Each page will have:
- [ ] list of sponsors
- [ ] list of events that link to meetup
- [ ] list of organizers
- [ ] stretch: a nice chapter-specific photo

## Motivation

- Improve awareness of our individual chapters
- Give a centralized location 
- Give chapter organizers ownership over their own pages for managing updates and data

## Questions

- Needs design
- Needs content model

**Comment by coilysiren** [comment]
There's currently 2 pages that I know we need:

```
# chapter page
https://www.writespeakcode.com/chapters/<chapter name>
# events page
https://www.writespeakcode.com/chapters/<chapter name>/events/<event name>
```

☝️ feel free to make the urls less verbose if you want. I could imaging something like

```
# chapter page
https://www.writespeakcode.com/<chapter name>
 where <chapter name> is:
   - chapter-sea
   - sea
# events page
https://www.writespeakcode.com/<event name>
 where <event name> is:
    - oye-sea-2019
```

## chapter page

On the chapter page I want:

- a list of our events _(pulled from meetup, with links back to meetup)_
- a list of local sponsors
  - this should be generated by adding a `chapters` or `locations` field to the existing sponsors list https://github.com/WriteSpeakCode/writespeakcode.com/tree/production/content/sponsors
- a list of organizers
  - pulled from https://github.com/WriteSpeakCode/writespeakcode.com/tree/production/content/organizers
  - should include a variety of required + optional data, required name, optional public email, required headshot _(IMO)_, etc etc _(we can work out this list later)_

eventually I want sub-pages that describe how to become a sponsor / organizer / host an event, but we can figure that out later IMO.

## events page

I want a page like the national conference page, but for OYEs https://www.writespeakcode.com/2019/

OYEs have all the same contact as the national conf _(eg. schedule, program, speaker list)_ so TBH we can use all the same style and structure, just swap in different content.

The primary goal here is to use this page to help drive requirements for OYE. That is, create a place where we can compare national events / EOY events against each other, and see where we can improve / plan ahead.

The secondary goal here is to create an alternate event front-page, in replacement of ti.to. That said, the MVP of this page will almost certainly include a link to ti.to somewhere.

**Comment by deweydell** [comment]
@lynncyrin I'm working on the Seattle chapter page! Do you have any photos specifically of the seattle chapter that I could use?

**Comment by coilysiren** [comment]
@deweydell I'll go find a bunch now, and collect them in google drive 👍

**Comment by coilysiren** [comment]
partially assigning this to myself so that I don't forget about it ^^
